### ISSUE TITLE
Why does file loader add an "_" to output directory paths?

### ISSUE THREAD

**Issue by jasonmacdonald** [webpack/file-loader#18]
I've tried searching everywhere I can but cannot figure out why File-loader, or more specifically the loader-utils, keep adding an "\_" directory to which it adds all my images loaded from CSS. Why is this happening? Why can I not use the same path from my /src directory without adding an "_" directory at the top?

**Comment by sokra** [comment]
I think this comes from `[path]` which is the location of your module relative to the provided context. And because you don't want output outside of your output directory `../` is replaced with `_/`.
You need to provide a better `context` to the loader to fix this.

https://github.com/webpack/loader-utils/blob/master/index.js#L196

> * [path] the path of the resource relative to the context query parameter or option.

**Comment by SpaceK33z** [comment]
Closing since this has been answered and is inactive.
