### ISSUE TITLE
Not able to copy an image file

### ISSUE THREAD

**Issue by 0x80** [webpack/file-loader#56]
I tried to copy an image from my folder static into the dist output like this

`require('file?name=foo.png!./static/foo.png')`

But the image always ended up being 80bytes and not the image as it should be (original is 90k). Could there be a clash when .png is also defined in a loader config?

My webpack image loader is configured like this

```
{
        test: /\.(png|jpe?g)$/,
        loaders: [
          'url?limit=10000',
          'image-webpack?bypassOnDebug&optimizationLevel=7&interlaced=false',
          'image-maxsize-webpack?useImageMagick=true'
        ]
      }
```

**Comment by Yankovsky** [comment]
Same problem

**Comment by allisonwhilden** [comment]
I'm new to all of this, and I don't know if this helps at all -- but I ran into what seemed like a similar problem. When checking out my emitted image files, they appeared to be smaller in size and wouldn't open at all. I changed the extension of these files to .txt and opened them in a text editor, and noticed that they appeared to be a shortened data URI string -- but not the complete one you would get if you converted your original image to a data URI string. 

Further investigation found that I appeared to have been running the files both through the URL-loader via my webpack config, and through file-loader in a similar 'require' statement in my CSS file. When I just used one or the other, everything worked out. So, if I commented out my URL-loader in my webpack config, my 'require' statement worked.

Don't know if this makes sense, is intentional, or is helpful at all -- I'm still very much learning all of this. But sharing it just in case it saves anyone else time.

**Comment by DevilZh** [comment]
Same +1

**Comment by flyingzl** [comment]
Same +1

My workaround is  : webpack.config.js

```javascript

            {
                test: /\.(png|jpg|gif)$/,
                exclude: /\.dp\.(png|jpg|gif)/,
                loader: "url",
                query: {
                    limit: 8192,
                    name: 'imgs/[name].[ext]'
                }
            },
```

Please pay attention to the `exclude`, if a image named with **foo.dp.png**, it will not be parsed by `url-loader`, and you can require import js file like the following:
```javascript
import icon from 'file-loader?name=imgs/[name].[ext]!./foo.dp.png';
console.log( icon )
```

**Comment by SpaceK33z** [comment]
You can't use the file-loader twice this way. What @flyingzl said is the best answer.
